### ISSUE TITLE
Unlicensed copy of Chaquopy: app will shut down in 10 seconds.

### ISSUE THREAD

**Issue by ZhangKuixun** [chaquo/chaquopy#71] opened 2018-12-05 07:00 UTC
way？there is error: Unlicensed copy of Chaquopy: app will shut down in 10 seconds.

E/[kevin_LOG]====WebViewFragment.getVideoUrl(L:713): WebView start get video url
W/python.stderr: Unlicensed copy of Chaquopy: app will shut down in 10 seconds.
W/python.stderr:  
W/python.stderr: WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL envi
I/python.stdout: [generic] sp.nicovideo: Requesting header
W/python.stderr: WARNING: Falling back on generic information extractor.
I/python.stdout: [generic] sp.nicovideo: Downloading webpage
I/python.stdout: [generic] sp.nicovideo: Extracting information
W/python.stderr: ERROR: Unsupported URL: http://sp.nicovideo.jp/
I/python.stdout: Error extracting info: Traceback (most recent call last):
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/YoutubeDL.py", line 792, in extract_info
I/python.stdout:     ie_result = ie.extract(url)
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/extractor/common.py", line 508, in extract
I/python.stdout:     ie_result = self._real_extract(url)
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/extractor/generic.py", line 3318, in _real_extract
I/python.stdout:     raise UnsupportedError(url)
I/python.stdout: youtube_dl.utils.UnsupportedError: Unsupported URL: http://sp.nicovideo.jp/
I/python.stdout:  
I/python.stdout: During handling of the above exception, another exception occurred:
I/python.stdout:  
I/python.stdout: Traceback (most recent call last):
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/__main__.py", line 58, in get_info
I/python.stdout:     meta = ydl.extract_info(url, download=False)
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/YoutubeDL.py", line 815, in extract_info
I/python.stdout:     self.report_error(compat_str(e), e.format_traceback())
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/YoutubeDL.py", line 620, in report_error
I/python.stdout:     self.trouble(error_message, tb)
I/python.stdout:   File "/android_asset/chaquopy/app.zip/youtube_dl/YoutubeDL.py", line 590, in trouble
I/python.stdout:     raise DownloadError(message, exc_info)
I/python.stdout: youtube_dl.utils.DownloadError: ERROR: Unsupported URL: http://sp.nicovideo.jp/
I/python.stdout:  
E/[kevin_LOG]====WebViewFragment.getVideoUrl(L:722): 地址为空
I/Choreographer: Skipped 338 frames!  The application may be doing too much work on its main thread.
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad: Chrome build fingerprint:
W/google-breakpad: 70.0.3538.110
W/google-breakpad: 353811052
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9905 (geana.FastVideo), pid 9323 (geana.FastVideo)

**Comment by mhsmith** [comment] 2018-12-05 11:14
Duplicate of #70.

**Closed by mhsmith** 2018-12-05 11:14 UTC
