### ISSUE TITLE
Please add chaquopy support to be built into a library module (AAR)

### ISSUE THREAD

**Issue by gecsbernat** [chaquo/chaquopy#94] opened 2019-03-12 16:34 UTC
I am trying to use chaquopy https://chaquo.com/chaquopy/ android plugin for developing an android app that uses python script for some serious calculations, and I would like to make the app module as an android library (.AAR) to be able to reuse that in other project. (.eg ionic app).

**Comment by audvi** [comment] 2019-05-28 08:40
Yes, that would be a really nice feature. I would need it too.

**Comment by mhsmith** [comment] 2019-05-28 11:44
If anyone else would like this feature, please subscribe to this issue and add a thumbs-up above.

**Comment by im-ranu** [comment] 2019-10-14 09:02
I need too

**Comment by SNVID** [comment] 2019-10-23 23:14
Agree - would be a great feature!

**Comment by VicentIborra** [comment] 2020-01-20 15:38
I need to use chaquopy plugin from an android library too.

**Comment by TheForgetTime** [comment] 2020-03-03 03:23
This feature is great

**Comment by VicentIborra** [comment] 2020-03-12 16:13
Hi, we need to use Python in an app module (com.android.library). It's possible to install ChaquoPy in a module with 7.0.2 version? Thanks!

**Comment by mhsmith** [comment] 2020-03-12 16:43
Currently Chaquopy can only be used in a top-level app, not in an AAR.

**Comment by VicentIborra** [comment] 2020-03-13 07:51
We need this feature for our project. It's scheduled to develop this function in Chaquopy?

**Comment by mhsmith** [comment] 2020-03-13 09:34
Can you give some details of your development workflow, and explain why you want to use Chaquopy in an AAR rather than directly in the top-level app?

**Comment by mhsmith** [comment] 2020-03-13 10:29
@audvi @im-ranu @SNVID @TheForgetTime: Can you answer question above? I'd like to understand why people need this feature.

**Comment by audvi** [comment] 2020-03-13 10:37
Hello,
We have an application that is chunked into modules. Some modules are generic and reused in different applications. The module that should use chaquopy is an implementation of the generic module.
To use chaquopy I had to destroy the complete architecture of the application and put back the  modules into the top level app. Now, the generic modules are dependant of the top level app to work which is an ugly implementation.


[cid:image006.png@01D5F92B.CD234B90]

Audrey VIDAL
DSYS/SSCE/LSSC

Commissariat à l’énergie atomique et aux énergies alternatives
MINATEC Campus | 17 rue des martyrs | F-38054 Grenoble Cedex
T. +33 (0)4 38 78 09 18
audrey.vidal@cea.fr<mailto:audrey.vidal@cea.fr>



De : Malcolm Smith <notifications@github.com>
Envoyé : vendredi 13 mars 2020 10:35
À : chaquo/chaquopy <chaquopy@noreply.github.com>
Cc : VIDAL Audrey 212854 <audrey.vidal@cea.fr>; Manual <manual@noreply.github.com>
Objet : Re: [chaquo/chaquopy] Please add chaquopy support to be built into an AAR (#94)


Can you give some details of your development workflow, and explain why you want to use Chaquopy in an AAR rather than directly in the top-level app?

**Comment by VicentIborra** [comment] 2020-03-13 10:53
Hi Malcolm,
We are developing a module for a project. This project is an Android app, but our module is only an optional part of this project. We need allow people of another University to work with the app without this module. We can't force people to install ChaquoPy, dependencies, Python libraries... They only need these features if they decide to install our module, so we need install Python from the module, not from the app.

**Comment by SNVID** [comment] 2020-03-13 10:59
Hi @mhsmith ,

I gave a thumbs up for this feature because my company has a Xamarin application that could make use of a separate python application we have. 

Xamarin cannot directly use Android code, however it can bind Android libraries for use.


BTW The native Android application we tested Chaquopy with worked wonderfully well as a top level app!

**Comment by mhsmith** [comment] 2020-03-13 12:15
Thanks everyone for your replies. I'm thinking of adding support for a single Chaquopy-based AAR per app. So your options would be either:

* Build Chaquopy into the top-level app, but not any AAR, as in the current version; or
* Build Chaquopy into exactly one AAR, but not the top-level app. The top-level app would still be able to use the Chaquopy API to access the AAR's Python code, but it wouldn't be able to contain any Python code of its own.

Would this solve your use cases?

**Comment by VicentIborra** [comment] 2020-03-13 12:29
Thanks Malcolm,
Could I build Chaquopy in the AAR and run Python scripts from this AAR? In this case, settings will be in gradle files of the module, right? Do I need some configuration in app level files?

**Comment by mhsmith** [comment] 2020-03-13 12:40
All the Python settings would be in the library module's build.gradle file, and there would be no changes required to the app-level files.

**Comment by VicentIborra** [comment] 2020-03-13 13:06
Thanks, I tested and I received this error (with ChaquoPy 6.3.0):

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':neurobehaviour'.
> Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':neurobehaviour'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:80)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:73)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$600(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject$1.run(LifecycleProjectEvaluator.java:112)
	at org.gradle.internal.Factories$1.create(Factories.java:26)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withProjectLock(DefaultProjectStateRegistry.java:227)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:221)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:187)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:96)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:693)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:141)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:36)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:64)
	at org.gradle.configuration.DefaultProjectsPreparer.prepareProjects(DefaultProjectsPreparer.java:55)
	at org.gradle.configuration.BuildOperatingFiringProjectsPreparer$ConfigureBuild.run(BuildOperatingFiringProjectsPreparer.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.BuildOperatingFiringProjectsPreparer.prepareProjects(BuildOperatingFiringProjectsPreparer.java:40)
	at org.gradle.initialization.DefaultGradleLauncher.prepareProjects(DefaultGradleLauncher.java:198)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:138)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:126)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:106)
	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:60)
	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:57)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:85)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:54)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:87)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.android.build.gradle.LibraryExtension_Decorated.getProperty(Unknown Source)
	at com.chaquo.python.PythonPlugin.afterEvaluate(PythonPlugin.groovy:182)
	at com.chaquo.python.PythonPlugin$_apply_closure2.doCall(PythonPlugin.groovy:54)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1$1.run(DefaultListenerBuildOperationDecorator.java:185)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:180)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:177)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy38.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:191)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:188)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1420)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:197)
	... 115 more


* Get more help at https://help.gradle.org

BUILD FAILED in 233ms

**Comment by mhsmith** [comment] 2020-03-13 15:06
Yes, it won't work in the current version, I was talking about a plan for the next version.

**Comment by bdovaz** [comment] 2020-03-19 19:05
Yes, please. I'm also developing an Android app in Xamarin that need to use this library to run some python code.

**Comment by aditmodhvadia** [comment] 2020-04-17 19:51
This would be a very useful feature. As it provides separation of concern and independence in development flow.

**Comment by mhsmith** [comment] 2020-06-15 16:32
This issue is fixed in Chaquopy 8.0.0. To upgrade, open your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle`.

As mentioned above, Chaquopy can still only be used in one module in a project: either in the app module, or in exactly one library module. Attempting to use it in multiple modules will give the error “More than one file was found with OS independent path”.

**Closed by mhsmith** 2020-06-15 16:32 UTC
Labels: enhancement

**Comment by vidheyoza** [comment] 2020-06-26 07:00
Hi, 

Thank you for the new release!

We use JitPack to easily sync up our library modules to the main app. I added a new release for the library and went to JitPack to import as dependency, but it is showing this error log: 

`A problem occurred starting process 'command 'python3''. Please set buildPython to your Python executable path. See https://chaquo.com/chaquopy/doc/current/android.html#buildpython.`

Also, I'm getting this error while trying to add the dependency: 

`Failed to resolve: com.github.organization:app-python-library:v0.0.1`

Are these issues connected? And how do I resolve them? I've passed the right dependencies for JitPack as well as Chaquopy.

**Comment by mhsmith** [comment] 2020-06-26 11:08
If you're using a service to build a Chaquopy-based module, then that service will need to have Python available. The only way to avoid this is if your module doesn't use any feature which runs Python at build time: specifically, the features in these sections of [the documentation](https://chaquo.com/chaquopy/doc/current/android.html):

* Requirements
* Bytecode compilation
* Static proxy generator

**Comment by vidheyoza** [comment] 2020-06-26 11:14
Okay, so the alternative would be to update the package manually on the main app whenever I make changes on the AAR right?

**Comment by mhsmith** [comment] 2020-06-26 11:25
I think your options are:

* Arrange for Python to be available on the JitPack server, if possible; or
* Build the AAR yourself rather than using JitPack.

**Comment by arnavpon** [comment] 2022-05-01 13:36
Hi Malcolm, 

I'm building a Flutter plugin that requires chaquopy as a dependency, but having a lot of trouble correctly configuring the build.gradle file. The main issue is that there's only one build.gradle in a Flutter plugin's android module (there's no app-specific build.gradle), so I tried to add all the necessary configuration to this file. When I try to build, here's the error I'm getting:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':pydroid:bundleDebugAar'.
> Could not resolve all files for configuration ':pythonRuntimeJava'.
   > Could not find com.chaquo.python.runtime:chaquopy_java:11.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/chaquo/python/runtime/chaquopy_java/11.0.0/chaquopy_java-11.0.0.pom
       - https://repo.maven.apache.org/maven2/com/chaquo/python/runtime/chaquopy_java/11.0.0/chaquopy_java-11.0.0.pom
     Required by:
         project :
```

And the build.gradle file:
```
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "com.chaquo.python:gradle:11.0.0"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'com.chaquo.python'

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            buildPython "~/opt/anaconda3/envs/chaquopy/bin/python3.8"
            pip {
                install 'numpy'
            }
        }
    }
}
```

Apologies in advance if I'm making an obvious error - I'm new to Android development. Thank you!

**Comment by arnavpon** [comment] 2022-05-05 01:32
Malcolm,

Thank you for being so responsive. I'm building a Flutter plugin that utilizes chaquopy. Configuring the module's _build.gradle_ as well as the top-level and app-level _build.gradle_ files in the "example" app as specified in the chaquopy docs enables a successful build. However, whenever I attempt to call any chaquopy code within the android plugin, the application crashes with the following exception:

<img width="747" alt="Screen Shot 2022-05-03 at 10 03 57 PM" src="https://user-images.githubusercontent.com/16437565/166851588-4f5acbd0-6e64-4539-a5c8-0e5615eded2b.png">

It's specifically the chaquopy code generating the error, as other data passed through the method channel, such as identifying the android OS build version, works as expected.
