### ISSUE TITLE
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

### ISSUE THREAD

**Issue by FabienNiel** [chaquo/chaquopy#403] opened 2020-11-27 13:48 UTC
Error when trying to run a project with chaquopy on macos. This error occurs only when uncommenting the pip part:
Build gradle file : 

```
        python {
            buildPython "python3.8"

            pyc {
               src true
            }
//            pip {
//                install "opencv-python"
//            }
        }

```

**Comment by mhsmith** [comment] 2020-11-27 13:54
Post the full build log please.

**Comment by mhsmith** [comment] 2020-12-02 14:55
Duplicate of #405.

**Closed by mhsmith** 2020-12-02 14:55 UTC
