### ISSUE TITLE
com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#118] opened 2019-06-19 21:58 UTC
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testdemo, PID: 18076
    java.lang.RuntimeException: Unable to create application com.testdemo.App: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at <python>.java.android.importer.initialize_importlib(importer.py:62)
        at <python>.java.android.importer.initialize(importer.py:40)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:130)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.chaquo.python.android.PyApplication.onCreate(PyApplication.java:16)
        at com.testdemo.App.onCreate(App.java:49)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by chaocharleswang** [comment] 2019-06-19 21:59
My project worked yesterday. But it does not work today without any changes.

**Comment by chaocharleswang** [comment] 2019-06-19 22:11
I switched chaquo to the old version 6.0.0. It worked again. Then I switched it back to the latest version 6.2.1. It works well again. Can you please check the problem?

**Comment by mhsmith** [comment] 2019-06-20 10:11
Duplicate of #57: please continue the discussion there.

**Closed by mhsmith** 2019-06-20 10:11 UTC
