### ISSUE TITLE
Extending View does not work

### ISSUE THREAD

**Issue by noknok200** [chaquo/chaquopy#76] opened 2018-12-17 15:54 UTC
I am trying to make a custom view called CanvasView, by extending Android.view.View like this:
```
class CanvasView(static_proxy(View, View.OnTouchListener)):

    @constructor([Context])
    def __init__(self, c):
        View(c)

    @constructor([Context, AttributeSet])
    def __init__(self, c, attr):
        View(c, attr)

    @constructor([Context, AttributeSet, jint])
    def __init__(self, c, attr, st):
        View(c, attr, st)
```
However, It gives me an error. It says that "no suitable constructor found for View(no arguments)"

**Comment by mhsmith** [comment] 2019-03-31 10:40
Duplicate of #10.

**Closed by mhsmith** 2019-03-31 10:40 UTC
Labels: enhancement, language
