### ISSUE TITLE
Failed to install sxtwl

### ISSUE THREAD

**Issue by mpadiy** [chaquo/chaquopy#854] opened 2023-04-13 07:01 UTC
Complete output from command "C:\Program Files (x86)\Python 3.8\python.exe" -u -S -c "import setuptools, tokenize;__file__='C:\\Users\\andy.ming\\AppData\\Local\\Temp\\pip-install-rn8spwnf\\sxtwl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\andy.ming\AppData\Local\Temp\pip-wheel-5gdmk11c --python-tag py3:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  copying sxtwl.py -> build\lib.win32-3.8
  running build_ext
  building '_sxtwl' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  
  ----------------------------------------
  Command ""C:\Program Files (x86)\Python 3.8\python.exe" -u -S -c "import setuptools, tokenize;__file__='C:\\Users\\andy.ming\\AppData\\Local\\Temp\\pip-install-rn8spwnf\\sxtwl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\andy.ming\AppData\Local\Temp\pip-wheel-5gdmk11c --python-tag py3" failed with error code 1 in C:\Users\andy.ming\AppData\Local\Temp\pip-install-rn8spwnf\sxtwl\
ERROR: Failed to install sxtwl from https://files.pythonhosted.org/packages/e7/8d/cef03bf70cd48e6a3ff0ed173710ab67fbbd98983c7f06dfc99b595ae304/sxtwl-2.0.6.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment] 2023-04-13 08:54
Duplicate of #855.

**Closed by mhsmith** 2023-04-13 08:54 UTC
