### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by aidenpierce2** [chaquo/chaquopy#519] opened 2021-07-16 07:48 UTC
hi
when i compile my code, i find a problem, i use a module named "process" and it required by another module
so i add 
pip {
              install "progress==1.3"
              xxx
              xxx
}
in my gradle
an then i occured the problem what i show on the title
so i search the problem on the web and someone tolded me "unescaped"  was removed after python3.4
unfortunatly i use python3.9 and i don't want to change my python version
can you tell me how to change the  setuptools in bp.zip file? i think if i could up setuptools version to the lastest this problem 
my be resloved
thanks!

**Comment by mhsmith** [comment] 2021-07-16 08:48
Duplicate of #416. Please search for existing issues before creating new ones.

**Closed by mhsmith** 2021-07-16 08:48 UTC

**Comment by aidenpierce2** [comment] 2021-07-16 09:25
thank you very mach! i changed my python version from 3.9.5 to 3.8.7, build successfully。it woked!
by the way，may i ask you when chaquo will update for verison 3.9 or above?

**Comment by mhsmith** [comment] 2021-07-16 09:29
It already has: see the last comment in #416.

**Comment by aidenpierce2** [comment] 2021-07-16 09:51
thanks!
