### ISSUE TITLE
Update package XGBoost

### ISSUE THREAD

**Issue by SnoopKilla** [chaquo/chaquopy#518] opened 2021-07-11 19:23 UTC
Hi,
I am trying to load an XGBClassifier model saved in a .json format from an Android app using Chaquopy but I get the following error:
`com.chaquo.python.PyException: XGBoostError: [21:21:49] xgboost/include/xgboost/json.h:65: Invalid cast, from Null to Array`
I think that I have spotted the problem, which is the version of XGBoost supported by Chaquopy (1.1.1). Indeed, the latest version is 1.4.2 and the possibility to load models from .json files was introduced in 1.3.0 if I did not misunderstand. Would it be possible to have an update of the package supported by Chaquopy?
Best regards.

**Comment by mhsmith** [comment] 2021-07-12 09:16
> the possibility to load models from .json files was introduced in 1.3.0 if I did not misunderstand

From the [XGBoost Change Log](https://github.com/dmlc/xgboost/blob/master/NEWS.md) it looks like it's actually been supported since 1.0.0. But there may have been some incompatible changes since 1.1.0. 

Can you try loading your json file on Windows, Mac or Linux with XGBoost 1.1.1, and see if you get the same error? And if so, is it fixed by using a newer version of XGBoost?

**Comment by mhsmith** [comment] 2021-07-12 09:17
Also, do you know which version of XGBoost was used to generate the file?

**Comment by SnoopKilla** [comment] 2021-07-12 09:43
Hi @mhsmith, thank you for your response. The version of XGBoost used to generate the model is 1.4.2. I have tried to generate the same model with XGBoost 1.1.1 and to use it with chaquopy and it worked, no error this time. It definitely looks like some incompatibility problem but it is no big deal since it doesn't seem like the performances of the classifier are any worse with XGBoost 1.1.1. Therefore I guess there is no need to update the package, altough it would be nice! I would be very happy to help if someone is willing to guide me through it

**Comment by mhsmith** [comment] 2021-07-12 10:55
OK, thanks for letting me know. I'll leave the issue open, and if anyone else needs an update of XGBoost, please click the thumbs up button above and leave a comment explaining why you need it.

**Comment by basrodriguez** [comment] 2021-09-08 01:50
Recently I paid for an individual license and now I have problem with XGBoost. I saved a model as .pkl and when I try to load I obtain the same error as above:
com.chaquo.python.PyException: XGBoostError: [03:18:25] xgboost/include/xgboost/json.h:65: Invalid cast, from Null to Array

I will be very grateful if I could install a version of XGBoost 1.3.0 or superior. ¿Is it possible? Thanks a lot.

**Comment by basrodriguez** [comment] 2021-09-08 07:36
> Hi @mhsmith, thank you for your response. The version of XGBoost used to generate the model is 1.4.2. I have tried to generate the same model with XGBoost 1.1.1 and to use it with chaquopy and it worked, no error this time. It definitely looks like some incompatibility problem but it is no big deal since it doesn't seem like the performances of the classifier are any worse with XGBoost 1.1.1. Therefore I guess there is no need to update the package, altough it would be nice! I would be very happy to help if someone is willing to guide me through it

Good Moorning,
       Where can I obtain XGBoost 1.1.1 in order to install in chaquopy. Do you have a link or file? Thanks a lot.

**Comment by mhsmith** [comment] 2021-09-08 13:01
>  I saved a model as .pkl and when I try to load I obtain the same error as above:

As @SnoopKilla discovered, the easiest way to work around this is to regenerate your model using XGBoost 1.1.1. That version is available on [conda-forge](https://anaconda.org/conda-forge/xgboost/files?version=1.1.1), but only for Mac and Linux, not Windows. It's available for Windows on [PyPI](https://pypi.org/project/xgboost/1.1.1/#files), but only in 64-bit. 

More recent versions are available for all three platforms on both [conda-forge](https://anaconda.org/conda-forge/xgboost/files?version=1.4.0) and [PyPI](https://pypi.org/project/xgboost/1.4.2/#files), but again only in 64-bit.

The Anaconda [main channel](https://repo.anaconda.com/pkgs/main) has an even more limited selection of versions, not including 1.1.1, and again only in 64-bit.

So I think your best option is to switch to a 64-bit environment, and then install the package from PyPI, unless you're on Mac or Linux, in which case you can also use conda-forge.

**Comment by basrodriguez** [comment] 2021-09-08 14:33
> > I saved a model as .pkl and when I try to load I obtain the same error as above:
> 
> As @SnoopKilla discovered, the easiest way to work around this is to regenerate your model using XGBoost 1.1.1. That version is available on [conda-forge](https://anaconda.org/conda-forge/xgboost/files?version=1.1.1), but only for Mac and Linux, not Windows. It's available for all three platforms on [PyPI](https://pypi.org/project/xgboost/1.1.1/#files), but only in 64-bit.
> 
> More recent versions are available for all three platforms on both [conda-forge](https://anaconda.org/conda-forge/xgboost/files?version=1.4.0) and [PyPI](https://pypi.org/project/xgboost/1.4.2/#files), but again only in 64-bit.
> 
> The Anaconda [main channel](https://repo.anaconda.com/pkgs/main) has an even more limited selection of versions, not including 1.1.1, and again only in 64-bit.
> 
> So I think your best option is to switch to a 64-bit environment, and then install the package from PyPI, unless you're on Mac or Linux, in which case you can also use conda-forge.

**Comment by basrodriguez** [comment] 2021-09-08 14:39
Thanks @mhsmith. The problem is that I'm using chaquopy under android and I think chaquopy only works under android in 32 bits, at least things related to load models. Please, can you confirm? When I worked in 64 bits I had problems with other models and, after read some articles, I changed to 32 bits and models went well (models not including xgboost).

Is not possible an update of XGBoost in chaquopy?

Thanks a lot.

**Comment by SnoopKilla** [comment] 2021-09-08 14:42
Hi @basrodriguez, I suggest you just install XGBoost 1.1.1 from pip on your windows device and save the model as a .pkl file from there. I had no problems using Windows 64 bit, so it should work for you as well.

**Comment by basrodriguez** [comment] 2021-09-08 23:23
> 
> 
> Hi @basrodriguez, I suggest you just install XGBoost 1.1.1 from pip on your windows device and save the model as a .pkl file from there. I had no problems using Windows 64 bit, so it should work for you as well.

Hi @SnoopKilla, I have just tried to run Android with a model without xgboost:

- Python under android -> 64 bits
- Fichero .pkl -> Generated with Anaconda/Python 64 bits

Result when trying to load the model:
    com.chaquo.python.PyException: ValueError: Buffer dtype mismatch, expected **'ITYPE_t' but got 'long long'**
        at <python>.sklearn.neighbors._kd_tree.get_memview_ITYPE_1D(_binary_tree.pxi:215)
        at <python>.sklearn.neighbors._kd_tree.BinaryTree._update_memviews(_binary_tree.pxi:1102)
        at <python>.sklearn.neighbors._kd_tree.BinaryTree.__setstate__(_binary_tree.pxi:1160)

Some weeks ago I look for this error and, as I remembered, the question is that chaquopy under Android only is possible python 32 bits.

Now, I continue working and "exactly the same code" works under 32 bits. Then I have to forget XGBoost until there was a solution. It's really a pity.

Thanks.

**Comment by mhsmith** [comment] 2021-09-10 12:09
> Some weeks ago I look for this error and, as I remembered, the question is that chaquopy under Android only is possible python 32 bits.

Where did you see that? We fully support all the current Android ABIs: armeabi-v7a, arm64-v8a, x86 and x86_64.

Your last example is from scikit-learn, which has various issues of its own with sharing models between different architectures and versions. For our current advice, see #168. And if that doesn't work, please create a separate issue and provide enough code for us to reproduce the problem.

But it doesn't look like xgboost depends on scikit-learn, so just because they both use the pkl file format doesn't mean they have the same level of support for sharing model files across platforms. I suggest you search the xgboost documentation and issue tracker for advice about that.

And as I said above, using a consistent version of XGBoost is likely to make things much easier.

**Comment by basrodriguez** [comment] 2021-09-10 16:53
Thanks a lot @mhsmith 
I'll try your advice with the same version both python and scikit-learn with 64 bits. As well I'll try xgboost with 64 bits (subject of this issue). I apologize for my comments, I thought chaquopy wasn't compatible with 64 bits.

I found this some weeks ago: https://www.programmersought.com/article/52778300879/

**Comment by mhsmith** [comment] 2021-09-10 21:30
Yes, that page isn't correct. He says he's calling `platform.architecture()` on Chaquopy, but from the output he's obviously running it on Windows.

**Comment by basrodriguez** [comment] 2021-09-13 09:42
Good Morning,
       I installed XGBoost 1.1.1 (64 bits) and run under chaquopy (64 bits) and model generated with 64 bits and it worked ok. Now I have to find out why I have problem with scikit-learn. If I cannot see the problem, I'll open a different issue.

Thank you both very much.

Regards.

**Comment by mhsmith** [comment] 2022-08-31 09:03
If anyone wants to try building the new version, follow the instructions [here](https://github.com/chaquo/build-wheel).  And if you're successful, please make a pull request so we can add the new version to the public repository.

**Comment by IsakTheHacker** [comment] 2023-01-16 15:56
Hi,
If anyone interested I have managed to update xgboost to the newest version in this [commit](https://github.com/IsakTheHacker/chaquopy-build-wheel/commit/7982ecb3d0ed49ebf35c6fbb2c423917f37c0258). Please do note that the newer version of xgboost also required an [update](https://github.com/IsakTheHacker/chaquopy-build-wheel/commit/c681b255481ba435ef966a4caf1db1e2c35be604) to CMake.

I hope this helps someone

**Closed** 2023-01-30 15:00 UTC
Labels: packages, update

**Comment by mhsmith** [comment] 2023-01-30 15:04
@IsakTheHacker: Thanks very much: I've built the new version and added it to our repository. 

Because this version was built against API level 21, it'll require Chaquopy 14.0.2 or later. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python`.

**Comment by kfchou** [comment] 2025-08-20 20:19
> Hi, If anyone interested I have managed to update xgboost to the newest version in this [commit](https://github.com/IsakTheHacker/chaquopy-build-wheel/commit/7982ecb3d0ed49ebf35c6fbb2c423917f37c0258). Please do note that the newer version of xgboost also required an [update](https://github.com/IsakTheHacker/chaquopy-build-wheel/commit/c681b255481ba435ef966a4caf1db1e2c35be604) to CMake.
> 
> I hope this helps someone

@IsakTheHacker curious how much effort it took you to update xgboost?
